[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Set production Node environment during build
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  autoLaunch = false
  port = 4321
  framework = "astro"

[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://images.unsplash.com https://images.pexels.com data:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "noarchive"

# Handle 404 errors with a custom page
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Redirect www to non-www
[[redirects]]
  from = "https://www.ranking-edmonton.netlify.app/*"
  to = "https://ranking-edmonton.netlify.app/:splat"
  status = 301
  force = true